apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-connection
spec:
  encryptedData:
    db: AgAic3Fvrfg/M/djbPgYIn2FmSswZCnwGtiXTPCWcG7flJ3zjKFzAnej1bxVODcSTw9KZhrHJUmYJKpQL9tcYhut+QXvdlgzlazhJFUOXOFSV/nxbG8KRalDyE2MoWGQTMyVpSsLCilutvvZ6D9enunm2jhEswUHnjgzMgoM0HDL45IDlTsJ5tbQspNJgGI1qQapoHUmVpj4qdMIV9kULMXqGMygDkvWMh2LIsxGWw39R5k0wuZFSmlDWvaYK3gefXW13qLwSiwN6ip7f0GXT5nxG0JGlv8dESEte2v41ppD0I8P7PVYLmcxa9vJHqkvljuuiGd/EeJcMDPJ0HEwmepb7dRDv6+P5UM36mJfRh5SVCjDXJLQ4R5ckPZuQwMWUDMzpR4EzLFl2ePz5l/ewa+MHlOzsMG4sWzY7LUzE0cJ5NnjPSf5pu375k7SuiyLuGLQ9pF3LVqFH8K/YFt8EppuKbI7cmTPFY4psJ5jw2cqSpkUDexax2Q2WotFd0Jg3SwVrP9hhc73dubs1g70Xn6OwS6tkd2QoNTcubnMI4aD1NT51uaLpVKcY8TC+1MbFmTj3wAAI6zUYyp6hs42RmJbxmF7e5QU2jlmnnhx17jkHOmtCCzur3Ns8eXpwVDJH2nywcLJCTLbKRZG85L6LfnlptQ5N/DDPtQWQqZvXKnoIDsw/v+urE3o5NRgSgtatsHdv0HdkkUu1s3qPsmCueV071V2I8zQVp0uI0Q5620BIc1tD1POWvZPXtYiWP9VdM0JA9gtgOau0RAz+l9eGBx3xx4dODydt27YlM3Iewu3KqPwSShztlpmdQRWxEN3uk0nRKue+X0=
  template:
    metadata:
      creationTimestamp: null
      name: database-connection

