apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-tile-server
spec:
  prefix: /tiles-next/
  rewrite: /
  cors: 
    origins:
      - https://prod-k8s.treetracker.org
    methods: GET
    headers:
      - Content-Type
      - Authorization
