---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-connection
  namespace: tile-server
spec:
  encryptedData:
    db: AgBiwQWZAqDogpcNVMNeRLtrV34BBIVINgqdb7bjScBvu3CccUao3xUv3dlHRhzBUFZ6JMVvwPafAQSIz63m0iLbotdA6u9XqmdQQL7odwD2Lt6qcMbWyst5qirqceTURNcyXuMmAN9EQdRW2Y+cAIkB1iB/+mWHroipqWLj7434wc5SLmKrNmMgN3DhRuc47hKlA71Uy0x1FOKpw9LQMKy611uBDPVwn8RcoFwB8kRRvLgjwGHJbCSngX/2cumj0MFJVTsHbs/Tnl+xgZslNopzKm2hW4i+IpSSIPNoqosYkUdcT6U020S0g1n2fye04iD8h+haG1jUGf3h0v61bpv7bv0/z8BTVOwJu2c4u2kWkZH1Gb9iTqAbVI2mZA6qEzp1Jby+5WizHdV5qRYrGZEJQTyjmfHeXU396vmkqYKHM00Pr8Di3tlNQvNIG+g85Pm9RxTzAGX4HvzwUpBp+tQOfjgHVuVb2OreN+tESL/xIJWmdD0oM0lSn7jzK2zf5btMz4KBBYtBs3MEW/i4wHAW94KvhkvDjsy3zi3AAgrhf241iLtYakuy3v2YFS9ehzwYBm0RZKB7hqvj+ddoDoW+ryXi2wE70TLES4Mw8hLASAZCBimnUwIGQLjvzcN9ZnxdjGr7ItjO0g4ATtns/Cue5JzY6ADlYmxqBxT2Nlqo43/tbJGZ1Rowm6dPMRwNH3q5e1GTmcZBPpn9O6caxCYu86yPuhhSeWdDqbsyltDmDnRlIhCi9iHWdpPedb2T8TcPDsYwgj+0CWy+ZR7a5lNxs75762sL7OvMmXnUgmx12VCEoCU8+iIfmsa+kDmHOTSszgyg06PnwXk=
  template:
    metadata:
      name: database-connection
      namespace: tile-server
